server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

# 后端网关地址：如果后端部署在宿主机 48080，则使用 host.docker.internal
    # Linux 环境运行容器时，需要增加：
    #   --add-host=host.docker.internal:host-gateway
    set $backend_upstream http://host.docker.internal:48080;
    location /admin-api/ {
        proxy_pass $backend_upstream;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /app-api/ {
        proxy_pass $backend_upstream;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
